export const d = {
  School: [
    {
      id: 1,
      name: "Greenwood High",
      location: "New York, USA",
      type: "School",
      courses: ["Science", "Arts", "Commerce"],
      website: "https://greenwoodhigh.edu",
      contact: "+1 234 567 890",
      scholarships: true,
      image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSzLH-E-ZiWlN4cXX7v3k5-HIIqs5nWC_3euA&s",
    },
    {
      id: 2,
      name: "Sunrise Public School",
      location: "California, USA",
      type: "School",
      courses: ["Math", "Science", "History"],
      website: "https://sunriseps.edu",
      contact: "+1 555 234 987",
      scholarships: false,
      image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSXmUZLXWV7bjq4JEKfH9no7rjNLQjdRFjOnA&s",
    },
    {
      id: 3,
      name: "Hillcrest Academy",
      location: "Texas, USA",
      type: "School",
      courses: ["English", "Physics", "Chemistry"],
      website: "https://hillcrestacademy.edu",
      contact: "+1 222 333 444",
      scholarships: true,
      image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSsbnyx8Y7g5tU3qrBUwvqwkvxazFID6bqaWA&s",
    },
    {
      id: 4,
      name: "Maple Leaf School",
      location: "Toronto, Canada",
      type: "School",
      courses: ["Math", "Arts", "Computer Studies"],
      website: "https://mapleleafschool.ca",
      contact: "+1 416 555 123",
      scholarships: true,
      image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRp7cM2VeCTt6xifk15q7YrX-qH9N7QuBnmvA&s",
    },
    {
      id: 5,
      name: "City Grammar School",
      location: "London, UK",
      type: "School",
      courses: ["Science", "Geography", "Economics"],
      website: "https://citygrammar.uk",
      contact: "+44 20 1234 5678",
      scholarships: false,
      image: "https://images.unsplash.com/photo-1588072432836-e10032774350?w=600",
    },
    {
      id: 6,
      name: "Elite International School",
      location: "Dubai, UAE",
      type: "School",
      courses: ["Science", "Math", "ICT"],
      website: "https://eliteintschool.ae",
      contact: "+971 4 567 321",
      scholarships: true,
      image: "https://images.unsplash.com/photo-1596495577886-d920f1fb7238?w=600",
    },
    {
      id: 7,
      name: "Bright Future Academy",
      location: "Sydney, Australia",
      type: "School",
      courses: ["Math", "Arts", "Science"],
      website: "https://brightfuture.edu.au",
      contact: "+61 2 1234 5678",
      scholarships: false,
      image: "https://images.unsplash.com/20/cambridge.JPG?q=80&w=847&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
    },
    {
      id: 8,
      name: "Harmony High School",
      location: "Berlin, Germany",
      type: "School",
      courses: ["Science", "Math", "Languages"],
      website: "https://harmonyhigh.de",
      contact: "+49 30 7654 321",
      scholarships: true,
      image: "https://images.unsplash.com/photo-1503676260728-1c00da094a0b?w=600",
    },
    {
      id: 9,
      name: "Riverdale High",
      location: "Chicago, USA",
      type: "School",
      courses: ["Science", "Sports", "Arts"],
      website: "https://riverdalehigh.edu",
      contact: "+1 312 555 987",
      scholarships: true,
      image: "https://images.unsplash.com/photo-1580587771525-78b9dba3b914?w=600",
    },
    {
      id: 10,
      name: "Oxford Public School",
      location: "Oxford, UK",
      type: "School",
      courses: ["Math", "Science", "Economics"],
      website: "https://oxfordps.uk",
      contact: "+44 1865 789654",
      scholarships: true,
      image: "https://images.unsplash.com/photo-1588072432836-e10032774350?w=600",
    },
  ],

  University: [
    {
      id: 1,
      name: "TechVille University",
      location: "San Francisco, USA",
      type: "University",
      courses: ["Computer Science", "Business Administration", "Design"],
      website: "https://techvilleuniv.edu",
      contact: "+1 987 654 321",
      scholarships: true,
      image: "https://images.unsplash.com/photo-1503676260728-1c00da094a0b?w=600",
    },
    {
      id: 2,
      name: "Global Business University",
      location: "London, UK",
      type: "University",
      courses: ["Finance", "Marketing", "Economics"],
      website: "https://gbu.ac.uk",
      contact: "+44 20 6543 987",
      scholarships: false,
      image: "https://images.unsplash.com/photo-1503676260728-1c00da094a0b?w=600",
    },
    {
      id: 3,
      name: "Pacific Technical University",
      location: "Los Angeles, USA",
      type: "University",
      courses: ["Engineering", "AI", "Data Science"],
      website: "https://pacifictech.edu",
      contact: "+1 213 555 432",
      scholarships: true,
      image: "https://images.unsplash.com/photo-1556761175-4b46a572b786?w=600",
    },
    {
      id: 4,
      name: "European Design Institute",
      location: "Milan, Italy",
      type: "University",
      courses: ["Graphic Design", "Fashion", "Architecture"],
      website: "https://edi.it",
      contact: "+39 02 9876 543",
      scholarships: false,
      image: "https://images.unsplash.com/20/cambridge.JPG?q=80&w=847&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
    },
    {
      id: 5,
      name: "National Institute of Technology",
      location: "Delhi, India",
      type: "University",
      courses: ["Engineering", "IT", "Mathematics"],
      website: "https://nitdelhi.ac.in",
      contact: "+91 11 2233 4455",
      scholarships: true,
      image: "https://images.unsplash.com/photo-1556761175-4b46a572b786?w=600",
    },
    {
      id: 6,
      name: "Sydney International University",
      location: "Sydney, Australia",
      type: "University",
      courses: ["Law", "Accounting", "Computer Science"],
      website: "https://siu.edu.au",
      contact: "+61 2 7654 321",
      scholarships: true,
      image: "https://images.unsplash.com/photo-1562774053-701939374585?w=600",
    },
    {
      id: 7,
      name: "Berlin Technical University",
      location: "Berlin, Germany",
      type: "University",
      courses: ["Engineering", "IT", "Physics"],
      website: "https://btu.de",
      contact: "+49 30 9988 776",
      scholarships: true,
      image: "https://images.unsplash.com/photo-1562774053-701939374585?q=80&w=886&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
    },
    {
      id: 8,
      name: "Tokyo Science University",
      location: "Tokyo, Japan",
      type: "University",
      courses: ["Robotics", "AI", "Mathematics"],
      website: "https://tsu.jp",
      contact: "+81 3 1234 5678",
      scholarships: false,
      image: "https://images.unsplash.com/photo-1720238189486-2b090d9a9459?q=80&w=870&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
    },
    {
      id: 9,
      name: "Harborview University",
      location: "Vancouver, Canada",
      type: "University",
      courses: ["Economics", "Computer Science", "Design"],
      website: "https://harborview.ca",
      contact: "+1 604 555 987",
      scholarships: true,
      image: "https://images.unsplash.com/photo-1571260899304-425eee4c7efc?w=600",
    },
    {
      id: 10,
      name: "Midwest State University",
      location: "Chicago, USA",
      type: "University",
      courses: ["Education", "Health Sciences", "Business"],
      website: "https://midwestuniv.edu",
      contact: "+1 312 789 123",
      scholarships: false,
      image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSyq71tlwU5_qf7MWdr1aY4daHfK82bXNgR7Q&s",
    },
  ],

  FreelancePlatforms: [
    {
      id: 1,
      name: "Upwork",
      website: "https://www.upwork.com",
      category: "Freelance Platform",
      founded: 2015,
      headquarters: "California, USA",
      freelancers: "20M+",
      popularSkills: ["Web Development", "SEO", "Graphic Design"],
      image: "https://images.unsplash.com/photo-1551836022-4c4c79ecde51?w=600",
    },
    {
      id: 2,
      name: "Fiverr",
      website: "https://www.fiverr.com",
      category: "Freelance Platform",
      founded: 2010,
      headquarters: "Tel Aviv, Israel",
      freelancers: "5M+",
      popularSkills: ["Writing", "Logo Design", "Marketing"],
      image: "https://images.unsplash.com/photo-1551434678-e076c223a692?w=600",
    },
    {
      id: 3,
      name: "Toptal",
      website: "https://www.toptal.com",
      category: "Freelance Platform",
      founded: 2010,
      headquarters: "Delaware, USA",
      freelancers: "10K+",
      popularSkills: ["Software Engineering", "Finance", "Product Design"],
      image: "https://images.unsplash.com/photo-1522202176988-66273c2fd55f?w=600",
    },
    {
      id: 4,
      name: "Guru",
      website: "https://www.guru.com",
      category: "Freelance Platform",
      founded: 2001,
      headquarters: "Pittsburgh, USA",
      freelancers: "3M+",
      popularSkills: ["Programming", "Translation", "Admin Support"],
      image: "https://images.unsplash.com/photo-1522075469751-3a6694fb2f61?w=600",
    },
    {
      id: 5,
      name: "PeoplePerHour",
      website: "https://www.peopleperhour.com",
      category: "Freelance Platform",
      founded: 2007,
      headquarters: "London, UK",
      freelancers: "1.5M+",
      popularSkills: ["Marketing", "Web Development", "Writing"],
      image: "https://images.unsplash.com/photo-1519389950473-47ba0277781c?w=600",
    },
    {
      id: 6,
      name: "Freelancer.com",
      website: "https://www.freelancer.com",
      category: "Freelance Platform",
      founded: 2009,
      headquarters: "Sydney, Australia",
      freelancers: "60M+",
      popularSkills: ["Data Entry", "Design", "IT"],
      image: "https://images.unsplash.com/photo-1521737604893-d14cc237f11d?w=600",
    },
    {
      id: 7,
      name: "99Designs",
      website: "https://www.99designs.com",
      category: "Freelance Platform",
      founded: 2008,
      headquarters: "Melbourne, Australia",
      freelancers: "100K+",
      popularSkills: ["Graphic Design", "Branding", "Illustration"],
      image: "https://images.unsplash.com/photo-1498050108023-c5249f4df085?w=600",
    },
    {
      id: 8,
      name: "DesignCrowd",
      website: "https://www.designcrowd.com",
      category: "Freelance Platform",
      founded: 2007,
      headquarters: "Sydney, Australia",
      freelancers: "700K+",
      popularSkills: ["Logo Design", "Graphic Design"],
      image: "https://images.unsplash.com/photo-1496317899792-9d7dbcd928a1?w=600",
    },
    {
      id: 9,
      name: "Workana",
      website: "https://www.workana.com",
      category: "Freelance Platform",
      founded: 2012,
      headquarters: "Buenos Aires, Argentina",
      freelancers: "2M+",
      popularSkills: ["Development", "Writing", "Translation"],
      image: "https://images.unsplash.com/photo-1519389950473-47ba0277781c?w=600",
    },
    {
      id: 10,
      name: "Truelancer",
      website: "https://www.truelancer.com",
      category: "Freelance Platform",
      founded: 2014,
      headquarters: "New Delhi, India",
      freelancers: "2M+",
      popularSkills: ["Web Development", "Design", "SEO"],
      image: "https://images.unsplash.com/photo-1487014679447-9f8336841d58?w=600",
    },
  ],

  JobPortals: [
    {
      id: 1,
      name: "LinkedIn Jobs",
      website: "https://www.linkedin.com/jobs",
      category: "Job Portal",
      country: "Global",
      employers: "100K+",
      image: "https://images.unsplash.com/photo-1504384308090-c894fdcc538d?w=600",
    },
    {
      id: 2,
      name: "Indeed",
      website: "https://www.indeed.com",
      category: "Job Portal",
      country: "Global",
      employers: "250K+",
      image: "https://images.unsplash.com/photo-1554224155-6726b3ff858f?w=600",
    },
    {
      id: 3,
      name: "Glassdoor",
      website: "https://www.glassdoor.com",
      category: "Job Portal",
      country: "Global",
      employers: "200K+",
      image: "https://images.unsplash.com/photo-1504384308090-c894fdcc538d?w=600",
    },
    {
      id: 4,
      name: "Monster",
      website: "https://www.monster.com",
      category: "Job Portal",
      country: "Global",
      employers: "150K+",
      image: "https://images.unsplash.com/photo-1556761175-4b46a572b786?w=600",
    },
    {
      id: 5,
      name: "Rozee.pk",
      website: "https://www.rozee.pk",
      category: "Job Portal",
      country: "Pakistan",
      employers: "20K+",
      image: "https://images.unsplash.com/photo-1519389950473-47ba0277781c?w=600",
    },
    {
      id: 6,
      name: "Bayt",
      website: "https://www.bayt.com",
      category: "Job Portal",
      country: "Middle East",
      employers: "30K+",
      image: "https://images.unsplash.com/photo-1498050108023-c5249f4df085?w=600",
    },
    {
      id: 7,
      name: "Naukri.com",
      website: "https://www.naukri.com",
      category: "Job Portal",
      country: "India",
      employers: "40K+",
      image: "https://images.unsplash.com/photo-1521737604893-d14cc237f11d?w=600",
    },
    {
      id: 8,
      name: "CareerBuilder",
      website: "https://www.careerbuilder.com",
      category: "Job Portal",
      country: "USA",
      employers: "60K+",
      image: "https://images.unsplash.com/photo-1556761175-4b46a572b786?w=600",
    },
    {
      id: 9,
      name: "JobStreet",
      website: "https://www.jobstreet.com",
      category: "Job Portal",
      country: "Asia-Pacific",
      employers: "35K+",
      image: "https://images.unsplash.com/photo-1519389950473-47ba0277781c?w=600",
    },
    {
      id: 10,
      name: "ZipRecruiter",
      website: "https://www.ziprecruiter.com",
      category: "Job Portal",
      country: "USA",
      employers: "50K+",
      image: "https://images.unsplash.com/photo-1504384308090-c894fdcc538d?w=600",
    },
  ],
};
